### ISSUE TITLE
How to enable gcmode=archive for client Reth

### ISSUE THREAD

**Issue by thanhnguyennguyen** [base/node#459]
How to enable gcmode=archive for client Reth

**Comment by thanhnguyennguyen** [comment]
To enable archive mode for Reth, we need to modify the docker-compose.yml file to add the --prune=false flag, which enables archive mode in Reth. I'll edit the docker-compose.yml file:

```
services:
  execution:
    build:
      context: .
      dockerfile: ${CLIENT:-geth}/Dockerfile
    ports:
      - "8545:8545" # RPC
      - "8546:8546" # websocket
      - "7301:6060" # metrics
      - "30303:30303" # P2P TCP
      - "30303:30303/udp" # P2P UDP
    command: ["bash", "./execution-entrypoint"]
    volumes:
      - ${HOST_DATA_DIR}:/data
    environment:
      - NODE_TYPE=${NODE_TYPE:-vanilla}
      - PRUNE_MODE=false  # Enable archive mode
    env_file:
      - ${NETWORK_ENV:-.env.mainnet} # Use .env.mainnet by default, override with .env.sepolia for testnet
// ... existing code ...
```

Now I need to modify the reth-entrypoint script to use this environment variable:

```
// ... existing code ...
exec $BINARY node \
  -vvv \
  --datadir="$RETH_DATA_DIR" \
  --log.stdout.format json \
  --ws \
  --ws.origins="*" \
  --ws.addr=0.0.0.0 \
  --ws.port="$WS_PORT" \
  --ws.api=debug,eth,net,txpool \
  --http \
  --http.corsdomain="*" \
  --http.addr=0.0.0.0 \
  --http.port="$RPC_PORT" \
  --http.api=debug,eth,net,txpool,miner \
  --ipcpath="$IPC_PATH" \
  --authrpc.addr=0.0.0.0 \
  --authrpc.port="$AUTHRPC_PORT" \
  --authrpc.jwtsecret="$OP_NODE_L2_ENGINE_AUTH" \
  --metrics=0.0.0.0:"$METRICS_PORT" \
  --max-outbound-peers=100 \
  --chain "$RETH_CHAIN" \
  --rollup.sequencer-http=$RETH_SEQUENCER_HTTP \
  --rollup.disable-tx-pool-gossip \
  ${PRUNE_MODE:+--prune=$PRUNE_MODE} \
  $ADDITIONAL_ARGS
```
